management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: distributed-rate-limiter

spring:
  data:
    redis:
      timeout: 200ms # Do not block threads if Redis hangs.
